export const ENTITY_CONFIG = {
  workflow: {
    table: "workflows",
    label: "Workflow",
    labelPlural: "Workflows",
    searchFields: ["name", "description"],
    labelField: "name",
    sortField: "created_at",
    sortOrder: "desc" as const,
    publicPath: "/api/public/workflows",
    protectedPath: "/api/cms/workflows",
  },
  integration: {
    table: "integrations",
    label: "Integration",
    labelPlural: "Integrations",
    searchFields: ["name", "provider"],
    labelField: "name",
    sortField: "created_at",
    sortOrder: "desc" as const,
    publicPath: "/api/public/integrations",
    protectedPath: "/api/cms/integrations",
  },
  skill: {
    table: "skills",
    label: "Skill",
    labelPlural: "Skills",
    searchFields: ["name", "description"],
    labelField: "name",
    sortField: "created_at",
    sortOrder: "desc" as const,
    publicPath: "/api/public/skills",
    protectedPath: "/api/cms/skills",
  },
  service: {
    table: "services",
    label: "Service",
    labelPlural: "Services",
    searchFields: ["name"],
    labelField: "name",
    sortField: "created_at",
    sortOrder: "desc" as const,
    publicPath: "/api/public/services",
    protectedPath: "/api/cms/services",
  },
  secret: {
    table: "secrets",
    label: "Secret",
    labelPlural: "Secrets",
    searchFields: ["name"],
    labelField: "name",
    sortField: "created_at",
    sortOrder: "desc" as const,
    publicPath: "/api/public/secrets",
    protectedPath: "/api/cms/secrets",
  },
  chat_session: {
    table: "chat_sessions",
    label: "Chat Session",
    labelPlural: "Chat Sessions",
    searchFields: ["title"],
    labelField: "title",
    sortField: "created_at",
    sortOrder: "desc" as const,
    publicPath: "/api/public/chat-sessions",
    protectedPath: "/api/cms/chat-sessions",
  },
  workflow_run: {
    table: "workflow_runs",
    label: "Workflow Run",
    labelPlural: "Workflow Runs",
    searchFields: [],
    labelField: "id",
    sortField: "started_at",
    sortOrder: "desc" as const,
    publicPath: "/api/public/workflow-runs",
    protectedPath: "/api/cms/workflow-runs",
  },
} as const;

export type EntityKey = keyof typeof ENTITY_CONFIG;
